services:
  svelte-kit:
    build:
      context: .
      dockerfile: ./docker/prod/bun/Dockerfile
      args:
        ORIGIN: "${ORIGIN:?err}"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      MARIADB_DATABASE: "${MARIADB_DATABASE:?err}"
      OPENAI_API_KEY: "${OPENAI_API_KEY:?err}"
      DATABASE_URL: "${DATABASE_URL:?err}"
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: fyc-svelte-kit
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/healthz || exit 1
      timeout: 20s
      retries: 10
      start_period: 60s
      interval: 60s
      start_interval: 1s

  mariadb:
    image: mariadb:11.1.2
    restart: unless-stopped
    container_name: fyc-mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_USER: "${MARIADB_USER:?err}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD:?err}"
      MARIADB_DATABASE: app
    healthcheck:
      test: ['CMD', 'mariadb-admin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
      start_period: 60s
      interval: 60s
      start_interval: 1s
